name: Build package

on: [push, pull_request]

jobs:
  php-build:
    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4]
        laravel: [8.*]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath
          coverage: pcov

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-suggest --ansi

      - name: Execute tests
        run: composer test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: .coverage/clover.xml
          fail_ci_if_error: true

  js-build:
    name: 'Install and build'
    needs: php-build
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta

      - name: Install dependencies
        run: yarn install

      # Remove any commited assert before building.
      - name: Build frontend production assets
        run: |           
          rm -rf /public/vendor/lighthouse-dashboard/js
          rm -rf /public/vendor/lighthouse-dashboard/css
          rm public/vendor/lighthouse-dashboard/mix-manifest.json
          yarn production

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:     
          message: "Automated fresh build for frontend assets"
       
